### ISSUE TITLE
[BUG]: Running "python main.py" doesn't do anything!

### ISSUE THREAD

**Issue by cyber-sec0** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#1000]
### Describe the bug

Running "python main.py" doesn't do anything!

**Comment by distortment** [comment]
Logs/more info please

**Comment by cyber-sec0** [comment]
Thanks for the quick response!

I'm using edge but I installed chrome just to test it.
I tried using py instead of python but that didn't work.

I ran it both on the folder directly using CMD and on vscode using the virtual environment.

I'm using Gemini.

I did change all files inside the data folder, and the config.py with the Gemini attributes.

I'm using W11...

Is this enough, or would you like me to share something else?

**Comment by m7saikat** [comment]
Running the code gives the following options to select. No option available for applying to the job

```
(venv) smukhopa@control Auto_Jobs_Applier_AIHawk % python main.py --resume ~/Downloads/Debamita_Resume.pdf                                                                                                                                                                                                    main
/Users/smukhopa/workspaces/leetcode/untitled/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
[?] Select the action you want to perform:: 
 > Generate Resume
   Generate Resume Tailored for Job Description
   Generate Tailored Cover Letter for Job Description
```

Here are some logs. Lot of 429 errors. The open API settings look good.  I have more than enough API usage limit.



```
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 429, b'Too Many Requests', [(b'Date', b'Fri, 06 Dec 2024 09:10:00 GMT'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Content-Length', b'337'), (b'Connection', b'keep-alive'), (b'vary', b'Origin'), (b'x-request-id', b'req_aecef359238a8bb67e29301df7e81fbf'), (b'strict-transport-security', b'max-age=31536000; includeSubDomains; preload'), (b'CF-Cache-Status', b'DYNAMIC'), (b'Set-Cookie', b'__cf_bm=bnJekMg.NICTW9G_cOGT1fU46xRYo0kcuL5GTiQ9ZmY-1733476200-1.0.1.1-CFJu8rYTcGvfr1RRRV6YVXvGCOfIfmGMNa4dLlW8sUZESSkzrbpGFupMu8J2N5AQGjBIRnKiXxYXZygBsA4cEA; path=/; expires=Fri, 06-Dec-24 09:40:00 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None'), (b'X-Content-Type-Options', b'nosniff'), (b'Set-Cookie', b'_cfuvid=N9bEDPU9sN7UkZ6OEQp.MMXx2Joh5MS2JoH78fGYkQ8-1733476200289-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None'), (b'Server', b'cloudflare'), (b'CF-RAY', b'8edb23eb1e433ba6-BOS'), (b'alt-svc', b'h3=":443"; ma=86400')])
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 429, b'Too Many Requests', [(b'Date', b'Fri, 06 Dec 2024 09:10:00 GMT'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Content-Length', b'337'), (b'Connection', b'keep-alive'), (b'vary', b'Origin'), (b'x-request-id', b'req_77e2c021dad875dfa64e7116e101141a'), (b'strict-transport-security', b'max-age=31536000; includeSubDomains; preload'), (b'CF-Cache-Status', b'DYNAMIC'), (b'Set-Cookie', b'__cf_bm=zWCAeqv2Lm2VZkMcleANgg7prlpL7LdI5W34r9466fQ-1733476200-1.0.1.1-aa0COd02BSxzCz7lV7iX2_kcvQU9afzk6SK7v9GsCGVENe3diJVo6u4t7r2xfGBvLLwGVBhe9UIOc_vPzb3UWQ; path=/; expires=Fri, 06-Dec-24 09:40:00 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None'), (b'X-Content-Type-Options', b'nosniff'), (b'Set-Cookie', b'_cfuvid=uy3Mkj.7.Lf6yj9gk2.hPM463zfYFqu8XsE.CzmLn14-1733476200288-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None'), (b'Server', b'cloudflare'), (b'CF-RAY', b'8edb23eb2f138f8a-BOS'), (b'alt-svc', b'h3=":443"; ma=86400')])
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:response_closed.complete
DEBUG:openai._base_client:HTTP Response: POST https://api.openai.com/v1/chat/completions "429 Too Many Requests" Headers([('date', 'Fri, 06 Dec 2024 09:10:00 GMT'), ('content-type', 'application/json; charset=utf-8'), ('content-length', '337'), ('connection', 'keep-alive'), ('vary', 'Origin'), ('x-request-id', 'req_aecef359238a8bb67e29301df7e81fbf'), ('strict-transport-security', 'max-age=31536000; includeSubDomains; preload'), ('cf-cache-status', 'DYNAMIC'), ('set-cookie', '__cf_bm=bnJekMg.NICTW9G_cOGT1fU46xRYo0kcuL5GTiQ9ZmY-1733476200-1.0.1.1-CFJu8rYTcGvfr1RRRV6YVXvGCOfIfmGMNa4dLlW8sUZESSkzrbpGFupMu8J2N5AQGjBIRnKiXxYXZygBsA4cEA; path=/; expires=Fri, 06-Dec-24 09:40:00 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None'), ('x-content-type-options', 'nosniff'), ('set-cookie', '_cfuvid=N9bEDPU9sN7UkZ6OEQp.MMXx2Joh5MS2JoH78fGYkQ8-1733476200289-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None'), ('server', 'cloudflare'), ('cf-ray', '8edb23eb1e433ba6-BOS'), ('alt-svc', 'h3=":443"; ma=86400')])
DEBUG:openai._base_client:HTTP Response: POST https://api.openai.com/v1/chat/completions "429 Too Many Requests" Headers([('date', 'Fri, 06 Dec 2024 09:10:00 GMT'), ('content-type', 'application/json; charset=utf-8'), ('content-length', '337'), ('connection', 'keep-alive'), ('vary', 'Origin'), ('x-request-id', 'req_77e2c021dad875dfa64e7116e101141a'), ('strict-transport-security', 'max-age=31536000; includeSubDomains; preload'), ('cf-cache-status', 'DYNAMIC'), ('set-cookie', '__cf_bm=zWCAeqv2Lm2VZkMcleANgg7prlpL7LdI5W34r9466fQ-1733476200-1.0.1.1-aa0COd02BSxzCz7lV7iX2_kcvQU9afzk6SK7v9GsCGVENe3diJVo6u4t7r2xfGBvLLwGVBhe9UIOc_vPzb3UWQ; path=/; expires=Fri, 06-Dec-24 09:40:00 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None'), ('x-content-type-options', 'nosniff'), ('set-cookie', '_cfuvid=uy3Mkj.7.Lf6yj9gk2.hPM463zfYFqu8XsE.CzmLn14-1733476200288-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None'), ('server', 'cloudflare'), ('cf-ray', '8edb23eb2f138f8a-BOS'), ('alt-svc', 'h3=":443"; ma=86400')])
DEBUG:openai._base_client:request_id: req_aecef359238a8bb67e29301df7e81fbf
DEBUG:openai._base_client:request_id: req_77e2c021dad875dfa64e7116e101141a
DEBUG:openai._base_client:Encountered httpx.HTTPStatusError
Traceback (most recent call last):
  File "/Users/smukhopa/workspaces/leetcode/untitled/venv/lib/python3.9/site-packages/openai/_base_client.py", line 1025, in _request
    response.raise_for_status()
  File "/Users/smukhopa/workspaces/leetcode/untitled/venv/lib/python3.9/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '429 Too Many Requests' for url 'https://api.openai.com/v1/chat/completions'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429
DEBUG:openai._base_client:Encountered httpx.HTTPStatusError
Traceback (most recent call last):
  File "/Users/smukhopa/workspaces/leetcode/untitled/venv/lib/python3.9/site-packages/openai/_base_client.py", line 1025, in _request
    response.raise_for_status()
  File "/Users/smukhopa/workspaces/leetcode/untitled/venv/lib/python3.9/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '429 Too Many Requests' for url 'https://api.openai.com/v1/chat/completions'

```

**Comment by cyber-sec0** [comment]
I haven't tried to run "python main.py --resume"

I saw on your video that you added email/password on the config file, but the docs don't say that and the current config file doesn't come with it, so I guess that's no longer needed?
Or is it not working because I haven't added it?

Please notice that your last update fails your python test, could this be the issue?

**Comment by jtcuth48** [comment]
Can confirm this behavior, even after git pull. Even looking at main.py, handle_inquiries is the last call made in the main function, which only generates the resume if you pick option 1 (nowhere are any attempts to apply to jobs made in the code anymore). Option 2 & 3 (generate tailored resume and tailored cover letter) straight up fail, both with username and password set in the config file, with the following error:

```
Client error '403 Forbidden' for url 'https://api.openai.com/v1/embeddings'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403
```

I think the documentation needs to be bolstered a bit - it feels like we're missing something obvious. Not to be harsh to the devs at all, I get maintaining FOSS is incredibly difficult, but it's gotten to where I feel like I'm wasting time messing with this bot that could be spent manually applying to jobs at this point until this is fixed.

**Comment by cyber-sec0** [comment]
I'm not even sure that this is happening (I haven't verified it) "the only thing this bot is doing is generating a resume for you.".

I'm glad that you are seeing an error message. I'm not seeing anything!

"I think the documentation needs to be bolstered a" TON! I already have another issue report opened mentioned many things, and I'm thinking about mentioning even more that I'm finding!

I tried to install the requirements.txt as mentioned on the documentation, but it never worked so I had to manually do it one by one!

**Comment by cyber-sec0** [comment]
I had no email and password, but even adding those didn't work.
I also removed the quotes from my API key, but that didn't change anything either

`email: eee
password: eee
llm_api_key: eee
`

**Comment by cyber-sec0** [comment]
Found the issue!

company_blacklist: and location_blacklist: can be left blank, but the issue was that I didn't use a tab spacing before the symbol - anywhere on my work_preferences.yaml file

This is a silly issue that's hard to notice... I thought that the program "parser" would be smarter and be able to handle that.
As soon as I added a tab before each - symbol, it worked.

Also, the video is old (Aug 7), so it should be redone.
It also shows that if I want to erase "achievements" etc, I have to go through the code and erase it in multiple files...
I recommend that the software "parser" should be smart enough and work with/without these file key names automatically, instead of requiring the user to "code".

The prompt
`
[?] Select the action you want to perform:: 
 > Generate Resume
   Generate Resume Tailored for Job Description
   Generate Tailored Cover Letter for Job Description
`

Looks like it's broken... Usually on terminal choosing options, the options are 1/2/3 and so forth. How do I even choose an option? Do I have to type the whole option text?
Btw, typing is also broken, typing any numbers/letters doesn't show anything... (Apparently, the number I typed is hidden but still works after I press enter)

After that I get a random language prompt [?] Quale stile vorresti adottare?: 
It should include links to the resume previews, not authors... Or should include links to both at least.

Now I'm stuck at this option.
[?] Please enter the URL of the job description:: 

Shouldn't the program auto-identify the job description of each job that it's looking at/applying for and generate my resume based on it? I'm not sure what this prompt means, because I thought that my previous question answer was "yes".
I left it empty and the program breaks with no error or any type of output.

Both commands below still ask me to generate a resume and force me to go through the same steps...
python main.py --resume "D:\Curriculum Vitae.docx"
python main.py --collect --resume "D:\Curriculum Vitae.docx"

**Comment by eromsubebe** [comment]
Similar experience as well. Running on Macos M1 . Openai API key configured as secret. Location is UK. Run the command: python main.py --resume <path to resume PDF> OR  python main.py . In both command, It prompts me to 1) [?] Select the action you want to perform:: 2) [?] Select a style for the resume::  And just stops. It throws no error [?] Select the action you want to perform::
 > Generate Resume
   Generate Resume Tailored for Job Description
   Generate Tailored Cover Letter for Job Description  [?] Select a style for the resume::
 > Clean Blue (style author -> https://github.com/samodum)
   Modern Blue (style author -> https://github.com/josylad)
   Modern Grey (style author -> https://github.com/josylad)
   Default (style author -> https://github.com/krishnavalliappan)
   Cloyola Grey (style author -> https://github.com/cloyola)

INFO:root:Selected style set to: Clean Blue

**Comment by cjbbb** [comment]
we will move all linkedin platform (due to linkedin police) coding and add support to other platforms in the future

**Comment by nxcxsx** [comment]
Same issue. The YT tutorial not having been updated is not only lazy but confusing and not relevant anymore.

**Comment by m7saikat** [comment]
The job application function has been removed. It is way different than the previous version. 

The `create_and_run_bot(parameters, llm_api_key)` function has been removed from main.py and replaced by a method that handles just three cases.

**Comment by jtcuth48** [comment]
Yup, and this was not communicated anywhere in the documentation, and was committed to master which appears to be being used as a WIP branch.

On Dec 8, 2024, at 11:17 AM, m7saikat ***@***.***> wrote:

﻿

The job application function has been removed. It is way different than the previous version.

The create_and_run_bot(parameters, llm_api_key) function has been removed from main.py and replaced by a method that handles just three cases.

**Comment by cyber-sec0** [comment]
@cjbbb

So the latest updates to the code were to break it and make it stop applying etc?

Now it's just a huge pile of coding and steps to generate a custom resume then? I would rather do it manually then.
This was disappointing...

Would LinkedIn sue anyone because of this program?
I highly doubt it, so why fear it then?

**Comment by cjbbb** [comment]
@cyber-sec0 LinkedIn connected with some of our team members, asked us to remove all the auto-job-applier function for LinkedIn Platform. They blocked most of contributors' accounts. In the future, we will consider to support for other platforms. It's very unfortunate that this used to be a great tool, but for the sake of others contributors in this project, we had to wipe out LinkedIn parts right now.

**Comment by jtcuth48** [comment]
@cjbbb, again, I mean no disrespect. But for future reference, this should've been communicated to the users via documentation, readme, or video. It should not have taken us opening an issue and asking over and over why the bot is no longer automatically applying. In fact, I STILL see no mention that LinkedIn functionality was removed in the readme.

**Comment by cyber-sec0** [comment]
Oh ok.
I forgot that they could also do that.

**Comment by cyber-sec0** [comment]
Oh ok.
I forgot that they could also do that.

**Comment by sarob** [comment]
Valid complaint. We moved quickly to limit the impact on users and contributors. Time to catch up and be as transparent as possible. Sean ***@***.*** On Dec 8, 2024, at 13:31, jtcuth48 ***@***.***> wrote:﻿
@cjbbb, again, I mean no disrespect. But for future reference, this should've been communicated to the users via documentation, readme, or video. It should not have taken us opening an issue and asking over and over why the bot is no longer automatically applying. In fact, I STILL see no mention that LinkedIn functionality was removed in the readme.

**Comment by surapuramakhil** [comment]
@sarob agreed 👍

**Comment by sarob** [comment]
We need to abide by the website’s ToS. We need to consider alternatives. Sean ***@***.*** On Dec 10, 2024, at 09:20, ddondada9 ***@***.***> wrote:﻿

@cyber-sec0 LinkedIn connected with some of our team members, asked us to remove all the auto-job-applier function for LinkedIn Platform. They blocked most of contributors' accounts. In the future, we will consider to support for other platforms. It's very unfortunate that this used to be a great tool, but for the sake of others contributors in this project, we had to wipe out LinkedIn parts right now.

OMG linkedin actually messaged you guys, that really sucks, howw long was the code working until they reached out? Is it possible to run something similar and make it more secret?

**Comment by craschnet** [comment]
Well time to boycott LinkedIn then. If they are preventing us from applying for a job, what use are they.

**Comment by ddondada9** [comment]
I don't get how when users want to use software they have an issue with it.
All we are doing is applying to jobs in a smarter way. There was a guy on
Fiverr who said he can make a bot for me. I told him that Linkedin has
cracked down on this application, which makes his own untouchable. He said
they don't change it often. How long was this bot running before Linkedin
cracked down on it.
ᐧ

**Comment by cyber-sec0** [comment]
I've no idea, but I would guess that it was working like 30 days ago...

Yes that's possible, but your account would still be banned if you used it, so there's no point.

-------- Original Message --------

**Comment by cyber-sec0** [comment]
Theyr aren't preventing us from applying for a job, we can all still apply manually.

-------- Original Message --------

**Comment by cyber-sec0** [comment]
That's the issue, we are being smart, not everyone is smart, which is "unfair" with dumb people who don't know how to install and run a python program.

LinkedIn thinks that everyone should have a fair chancenof applying to jobs, which means manual work.

-------- Original Message --------

**Comment by ddondada9** [comment]
We still have the same chance, its just the volume is way more for us. But
i guess back to applying manually, im transitioning to a new data analyst
role and my resume cant compete with someone who has experience in that
field, was hoping this will give me a chance for a junior role.
ᐧ

**Comment by franciscof5** [comment]
Another alternative is to move to 

https://radicle.xyz/

Descentralized annonymous git protocol... Just using fake names and get back to the game... but without the hero reputation the contributors deserve... It was a GREAT project and LinkedIn is a shixhole for woke and LGBT algorithim...

**Comment by jtcuth48** [comment]
...and with that I'm unsubscribing from this issue. Someone's always gotta make things political.
________________________________
