### ISSUE TITLE
[BUG]: Incorrect Option Selection

### ISSUE THREAD

**Issue by nihalmpatel** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#485]
### Describe the bug

The script is overriding the default option to incorrect value

### Steps to reproduce

I have specified the phone_prefix as "+1" but it uses a random value "+243" to populate the phone prefix and clears the email field.

Logs:

2024-10-06 18:05:29.799 | DEBUG    | src.aihawk_easy_applier:_find_and_handle_dropdown_question:755 - Dropdown options found: ['Select an option', 'Canada (+1)', 'Afghanistan (+93)', 'Aland Islands (+358)', 'Albania (+355)', 'Algeria (+213)', 'American Samoa (+1)', 'Andorra (+376)', 'Angola (+244)', 'Anguilla (+1)', 'Antarctica (+0)', 'Antigua and Barbuda (+1)', 'Argentina (+54)', 'Armenia (+374)', 'Aruba (+297)', 'Australia (+61)', 'Austria (+43)', 'Azerbaijan (+994)', 'Bahamas (+1)', 'Bahrain (+973)', 'Bangladesh (+880)', 'Barbados (+1)', 'Belarus (+375)', 'Belgium (+32)', 'Belize (+501)', 'Benin (+229)', 'Bermuda (+1)', 'Bhutan (+975)', 'Bolivia (+591)', 'Bosnia and Herzegovina (+387)', 'Botswana (+267)', 'Bouvet Island (+0)', 'Brazil (+55)', 'British Indian Ocean Territory (+246)', 'Brunei Darussalam (+673)', 'Bulgaria (+359)', 'Burkina Faso (+226)', 'Burundi (+257)', 'Cambodia (+855)', 'Cameroon (+237)', 'Cape Verde (+238)', 'Caribbean Nations (+0)', 'Cayman Islands (+1)', 'Central African Republic (+236)', 'Chad (+235)', 'Chile (+56)', 'China (+86)', 'Christmas Island (+61)', 'Cocos (Keeling) Islands (+61)', 'Colombia (+57)', 'Comoros (+269)', 'Congo (+242)', 'Cook Islands (+682)', 'Costa Rica (+506)', 'Cote D’Ivoire (Ivory Coast) (+225)', 'Croatia (+385)', 'Cuba (+53)', 'Cyprus (+357)', 'Czech Republic (+420)', 'Democratic Republic of the Congo (+243)', 'Denmark (+45)', 'Djibouti (+253)', 'Dominica (+1)', 'Dominican Republic (+1)', 'Ecuador (+593)', 'Egypt (+20)', 'El Salvador (+503)', 'Equatorial Guinea (+240)', 'Eritrea (+291)', 'Estonia (+372)', 'Ethiopia (+251)', 'Falkland Islands (Malvinas) (+500)', 'Faroe Islands (+298)', 'Federated States of Micronesia (+691)', 'Fiji (+679)', 'Finland (+358)', 'France (+33)', 'French Guiana (+594)', 'French Polynesia (+689)', 'French Southern Territories (+0)', 'Gabon (+241)', 'Gambia (+220)', 'Georgia (+995)', 'Germany (+49)', 'Ghana (+233)', 'Gibraltar (+350)', 'Greece (+30)', 'Greenland (+299)', 'Grenada (+1)', 'Guadeloupe (+590)', 'Guam (+1)', 'Guatemala (+502)', 'Guernsey (+44)', 'Guinea (+224)', 'Guinea-Bissau (+245)', 'Guyana (+592)', 'Haiti (+509)', 'Heard Island and McDonald Islands (+0)', 'Honduras (+504)', 'Hong Kong (+852)', 'Hungary (+36)', 'Iceland (+354)', 'India (+91)', 'Indonesia (+62)', 'Iran (+98)', 'Iraq (+964)', 'Ireland (+353)', 'Isle of Man (+44)', 'Israel (+972)', 'Italy (+39)', 'Jamaica (+1)', 'Japan (+81)', 'Jersey (+44)', 'Jordan (+962)', 'Kazakhstan (+7)', 'Kenya (+254)', 'Kiribati (+686)', 'Korea (+82)', 'Korea (North) (+850)', 'Kosovo (+383)', 'Kuwait (+965)', 'Kyrgyzstan (+996)', 'Laos (+856)', 'Latvia (+371)', 'Lebanon (+961)', 'Lesotho (+266)', 'Liberia (+231)', 'Libya (+218)', 'Liechtenstein (+423)', 'Lithuania (+370)', 'Luxembourg (+352)', 'Macao (+853)', 'Macedonia (+389)', 'Madagascar (+261)', 'Malawi (+265)', 'Malaysia (+60)', 'Maldives (+960)', 'Mali (+223)', 'Malta (+356)', 'Marshall Islands (+692)', 'Martinique (+596)', 'Mauritania (+222)', 'Mauritius (+230)', 'Mayotte (+262)', 'Mexico (+52)', 'Moldova (+373)', 'Monaco (+377)', 'Mongolia (+976)', 'Montenegro (+382)', 'Montserrat (+1)', 'Morocco (+212)', 'Mozambique (+258)', 'Myanmar (+95)', 'Namibia (+264)', 'Nauru (+674)', 'Nepal (+977)', 'Netherlands (+31)', 'Netherlands Antilles (+0)', 'New Caledonia (+687)', 'New Zealand (+64)', 'Nicaragua (+505)', 'Niger (+227)', 'Nigeria (+234)', 'Niue (+683)', 'Norfolk Island (+672)', 'Northern Mariana Islands (+1)', 'Norway (+47)', 'Pakistan (+92)', 'Palau (+680)', 'Palestinian Territory (+970)', 'Panama (+507)', 'Papua New Guinea (+675)', 'Paraguay (+595)', 'Peru (+51)', 'Philippines (+63)', 'Pitcairn (+0)', 'Poland (+48)', 'Portugal (+351)', 'Puerto Rico (+1)', 'Qatar (+974)', 'Reunion (+262)', 'Romania (+40)', 'Russian Federation (+7)', 'Rwanda (+250)', 'S. Georgia and S. Sandwich Islands (+0)', 'Saint Helena (+290)', 'Saint Kitts and Nevis (+1)', 'Saint Lucia (+1)', 'Saint Pierre and Miquelon (+508)', 'Saint Vincent and the Grenadines (+1)', 'Samoa (+685)', 'San Marino (+378)', 'Sao Tome and Principe (+239)', 'Saudi Arabia (+966)', 'Senegal (+221)', 'Serbia (+381)', 'Serbia and Montenegro (+0)', 'Seychelles (+248)', 'Sierra Leone (+232)', 'Singapore (+65)', 'Slovak Republic (+421)', 'Slovenia (+386)', 'Solomon Islands (+677)', 'Somalia (+252)', 'South Africa (+27)', 'South Sudan (+211)', 'Spain (+34)', 'Sri Lanka (+94)', 'Sudan (+249)', 'Sultanate of Oman (+968)', 'Suriname (+597)', 'Svalbard and Jan Mayen (+47)', 'Swaziland (+268)', 'Sweden (+46)', 'Switzerland (+41)', 'Syria (+963)', 'Taiwan (+886)', 'Tajikistan (+992)', 'Tanzania (+255)', 'Thailand (+66)', 'Timor-Leste (+670)', 'Togo (+228)', 'Tokelau (+690)', 'Tonga (+676)', 'Trinidad and Tobago (+1)', 'Tunisia (+216)', 'Turkey (+90)', 'Turkmenistan (+993)', 'Turks and Caicos Islands (+1)', 'Tuvalu (+688)', 'Uganda (+256)', 'Ukraine (+380)', 'United Arab Emirates (+971)', 'United Kingdom (+44)', 'United States (+1)', 'Uruguay (+598)', 'Uzbekistan (+998)', 'Vanuatu (+678)', 'Vatican City State (Holy See) (+39)', 'Venezuela (+58)', 'Vietnam (+84)', 'Virgin Islands (British) (+1)', 'Virgin Islands (U.S.) (+1)', 'Wallis and Futuna (+681)', 'Western Sahara (+212)', 'Yemen (+967)', 'Zambia (+260)', 'Zimbabwe (+263)']
2024-10-06 18:05:29.817 | DEBUG    | src.aihawk_easy_applier:_find_and_handle_dropdown_question:758 - Processing dropdown or combobox question: phone country code
phone country code
2024-10-06 18:05:29.866 | DEBUG    | src.aihawk_easy_applier:_find_and_handle_dropdown_question:761 - Current selection: Canada (+1)
2024-10-06 18:05:29.866 | DEBUG    | src.aihawk_easy_applier:_sanitize_text:849 - Sanitized text: phone country codephone country code
2024-10-06 18:05:29.866 | DEBUG    | src.aihawk_easy_applier:_sanitize_text:849 - Sanitized text: phone country codephone country code
2024-10-06 18:05:29.867 | DEBUG    | src.aihawk_easy_applier:_find_and_handle_dropdown_question:770 - Found existing answer for question 'phone country code
phone country code': Democratic Republic of the Congo (+243)
2024-10-06 18:05:29.867 | DEBUG    | src.aihawk_easy_applier:_find_and_handle_dropdown_question:772 - Updating selection to: Democratic Republic of the Congo (+243)

2024-10-06 18:05:31.363 | DEBUG    | src.aihawk_easy_applier:_find_and_handle_textbox_question:711 - Selected first option from the dropdown.
2024-10-06 18:05:31.363 | DEBUG    | src.aihawk_easy_applier:_process_form_section:619 - Handled textbox question
2024-10-06 18:05:31.363 | DEBUG    | src.aihawk_easy_applier:_process_form_section:611 - Processing form section
2024-10-06 18:05:31.432 | DEBUG    | src.aihawk_easy_applier:_find_and_handle_textbox_question:664 - Searching for text fields in the section.
2024-10-06 18:05:31.447 | DEBUG    | src.aihawk_easy_applier:_find_and_handle_textbox_question:714 - No text fields found in the section.
2024-10-06 18:05:31.518 | DEBUG    | src.aihawk_easy_applier:_find_and_handle_dropdown_question:755 - Dropdown options found: ['Select an option', 'username@gmail.com']
2024-10-06 18:05:31.538 | DEBUG    | src.aihawk_easy_applier:_find_and_handle_dropdown_question:758 - Processing dropdown or combobox question: email address
email address
2024-10-06 18:05:31.571 | DEBUG    | src.aihawk_easy_applier:_find_and_handle_dropdown_question:761 - Current selection: username@gmail.com
2024-10-06 18:05:31.571 | DEBUG    | src.aihawk_easy_applier:_sanitize_text:849 - Sanitized text: email addressemail address
2024-10-06 18:05:31.571 | DEBUG    | src.aihawk_easy_applier:_find_and_handle_dropdown_question:770 - Found existing answer for question 'email address
email address': Select an option
2024-10-06 18:05:31.572 | DEBUG    | src.aihawk_easy_applier:_find_and_handle_dropdown_question:772 - Updating selection to: Select an option
2024-10-06 18:05:31.572 | DEBUG    | src.aihawk_easy_applier:_select_dropdown_option:816 - Selecting dropdown option: Select an option
2024-10-06 18:05:31.645 | DEBUG    | src.aihawk_easy_applier:_process_form_section:626 - Handled dropdown question
2024-10-06 18:05:31.645 | DEBUG    | src.aihawk_easy_applier:_next_or_submit:284 - Clicking 'Next' or 'Submit' button
2024-10-06 18:05:38.562 | DEBUG    | src.aihawk_easy_applier:_check_for_errors:309 - Checking for form errors
2024-10-06 18:05:38.573 | ERROR    | src.aihawk_easy_applier:_check_for_errors:312 - Form submission failed with errors: [<selenium.webdriver.remote.webelement.WebElement (session="d0ad02fc3f3c70023d120dfb9fa95bd1", element="f.67C21F2DA6D903864CB7C9B3A4AFAD59.d.7D7D48DF8FFD6129C2B3B21F2604C76A.e.734")>]
2024-10-06 18:05:38.587 | ERROR    | src.aihawk_easy_applier:job_apply:143 - Failed to apply to job: Job(title='Principal Software Engineer, Documents', company='Coalition, Inc.', location='Canada (Remote)', link='https://www.linkedin.com/jobs/view/3970063046/', apply_method='Easy Apply', description="About the job\nAbout us\nCoalition is the world's first Active Insurance provider designed to help prevent digital risk before it strikes. Founded in 2017, Coalition combines broad insurance coverage with a digital risk assessment and continuous security monitoring to help organizations protect themselves in today’s hyper-connected world.\n\nOpportunities to make an impact with bold thinking are real - and happening daily.\n About the role\nAs a Principal Engineer on the document team, your role holds immense significance in shaping the trajectory of our company. Your wide-ranging experiences, professional concepts, and deep understanding of engineering will be instrumental in supporting our company objectives and tackling complex challenges with creativity and effectiveness. Your expertise will be pivotal in defining technology strategies that directly address critical business problems, leading to the delivery of innovative solutions that set new benchmarks.\n\nWithin our team, you will not only be at the forefront of defining team architecture and technical solutions but also wield influence that extends to related teams and your team members during projects. Your impact on software architecture, performance enhancements, and overall business value will be profound, leaving a lasting imprint on our organization's success.\n\nAs a natural leader within the team, you will have the opportunity to mentor and coach other engineers, guiding them in the art of designing, developing, testing, and deploying software. Your leadership will inspire excellence and elevate the capabilities of the entire team, amplifying our collective potential to achieve resilience and quality.\n\nWith your visionary guidance and technical prowess, our documents team will redefine the efficiency and effectiveness of document generation.\n\nResponsibilities\n\nUtilize wide-ranging experience, professional concepts, and company objectives to creatively and effectively resolve complex issues.\n\nDefine technology strategies to address business problems and deliver solutions independently.\n\nFocus on team architecture and product solutions, extending influence to related teams during projects.\n\nHands on coding and delivery, while also offering guidance and support for other engineers on the team.\n\nDeliver and lead high impact projects and solutions\n\nSolve complex software problems with visible risks, roadblocks, and constraints, ensuring solutions are extensible and scalable.\n\nImpact software architecture, dependencies, performance, and business value through innovative approaches.\n\nDesign, develop, test, and deploy software, while demonstrating leadership in managing large projects and delegating work for a small team of SDEs.\n\nProactively simplify code and resolve team architecture dependencies, taking a tactical and strategic approach to work.\n\nMitigate long-term risks and find viable paths forward in difficult situations.\n\nLead projects aimed at streamlining team processes and implementing mechanisms to reduce churn during implementation.\n\nExhibit self-driven and self-motivated behavior, actively finding time to prototype new ideas and resolving significant engineering problems without specific direction.\n\nCommunicate proactively and positively with teams across engineering, taking responsibility for communication on larger projects.\n\nInfluence peers, managers, PMs, and directors, actively mentoring individuals and driving learning opportunities for the entire team, such as brown bags and learning series.\n\n\nSkills and Qualifications\n\n Technical Skills:\n\n\n\nProven hands-on coding experience in developing complex software applications.\n\nDeep understanding of microservice architectural design, with a specific focus on business logic.\n\nProficient in mentoring and guiding the team on design patterns and potential pitfalls.\n\n\n\n Operational Experience:\n\n\n\nPrevious experience managing on-call duties for incident response, ensuring the team's ability to handle and resolve issues efficiently.\n\nDemonstrated expertise in implementing monitoring and observability practices for maintaining system health and performance.\n\nProven track record of enhancing team practices to achieve improved reliability and performance.\n\n\n\n Quality Focus:\n\n\n\nA strong background in elevating software quality within a team.\n\nAbility to guide and promote testing, continuous integration and deployment (CI/CD), code reviews, and other quality practices to ensure robust and bug-free software.\n\n\n\n Communication and Collaboration:\n\n\n\nExcellent communication skills, both written and verbal, with the ability to effectively convey technical concepts to team members and stakeholders.\n\nA collaborative and team-oriented mindset, capable of working effectively in a diverse and fast-paced environment.\n\nAble to communicate pros and cons of solutions as well as garner buy in for leaders on technical investment\n\n\n\n Problem-solving and Leadership:\n\n\n\nStrong problem-solving skills to analyze complex technical issues and devise effective solutions.\n\nLeadership capabilities to inspire and mentor team members, fostering a culture of continuous improvement and excellence.\n\n\n\n Customer Focused\n\n\n\nStrong customer focus and focused on building solutions that enable our business stakeholders\n\nA focus on building solutions for other teams that enable their efficiency and velocity via creative tooling\n\n\nBonus Points\n\nExperience in Document Generation: Expertise in working with document generation related services\n\nTemplate Management Proficiency: Experience in handling template related services to create and manage document templates\n\nBackend and Front End Experience: Experience in full stack development \n\nScaling Document Generation: A background in scaling document generation processes to handle increased demands efficiently\n\nAccuracy and Precision: The ability to prioritize accuracy and precision in document generation\n\nProject Management: Experience in managing cross team technical projects\n\n\nPerks\n\n100% medical, dental and vision coverage\n\nFlexible PTO policy\n\nAnnual home office stipend and WeWork access\n\nMental & physical health wellness programs (One Medical, Headspace, Gympass, and more)!\n\nCompetitive compensation and opportunity for advancement\n\n Why Coalition? \nWe’re a remote-first, mission-driven team committed to building a more inclusive culture with people of all different backgrounds. We trust our team members to take responsibility, share ownership, and put in the work to help us in our pursuit to solve digital risk.\n\nCoalition’s exceptional growth stems from its ability to address real-world problems for organizations of all sizes and remain true to our founding values of character, humility, responsibility, purpose, authenticity, and inclusion. \n\nWe’re always looking for collaborative, inquisitive individuals to join #OurCoalition.\n\nVisit our Newsroom >\n\n \nPrivacy Notice\nCoalition is committed to protecting your privacy. We want you to understand what personal information we collect and how we use it. We also want you to understand your options regarding our collection, use, and disclosure of such information and your ability to access and correct such information. As the leading provider of active insurance, Coalition is required to adhere to certain local regulations, including U.S. federal and state laws that protect your information and our use and disclosure of it.\n\nInformation submitted, collected, and processed as part of your application is subject to Coalition's Privacy Policy.\n\nAnti-Discrimination Notice\nCoalition is proud to be an Equal Opportunity employer. It is our policy to provide equal opportunity to all individuals seeking employment without regard to race, color, religion, religious creed, national origin, age, sex, marital status, ancestry, physical or mental disability, military or veteran status, gender, gender identity, gender expression, sexual orientation, medical condition, genetic information, or any other protected category under federal, state, or local law. We also prohibit harassment or discrimination of applicants based on the above-protected categories. This policy covers all aspects of employment, including but not limited to, recruitment, selection, training, promotion, transfer, compensation, demotion, and termination of employment.\n\nAccommodations\nCoalition complies with US federal and state disability laws. Our policy is to provide reasonable accommodations to qualified individuals with disabilities, including applicants and employees unless the accommodation imposes an undue hardship. Contact us by emailing candidateaccommodations@coalitioninc.com if you require reasonable accommodation to complete this application, interview, pre-employment testing, or participating in the employee selection process.\n\nWe consider qualified applicants, regardless of criminal histories, consistent with legal requirements.\n\nTo all recruitment agencies: Coalition does not accept unsolicited agency resumes. Do not forward resumes to our email alias, employees, or other physical or virtual organization locations. Coalition is not responsible for any fees related to unsolicited resumes.", summarize_job_description='**Technical Skills**\n\n1. Proven hands-on coding experience in developing complex software applications\n2. Deep understanding of microservice architectural design with a focus on business logic\n3. Proficient in mentoring and guiding the team on design patterns and potential pitfalls\n4. Experience managing on-call duties for incident response\n5. Demonstrated expertise in implementing monitoring and observability practices\n6. Strong background in elevating software quality within a team\n7. Ability to guide and promote testing, continuous integration and deployment (CI/CD), code reviews, and other quality practices\n8. Proficient in handling template-related services for document generation\n\n**Soft Skills**\n\n1. Excellent communication skills, both written and verbal\n2. Collaborative and team-oriented mindset\n3. Strong problem-solving skills to analyze complex technical issues\n4. Leadership capabilities to inspire and mentor team members\n5. Focused on building solutions that enable business stakeholders\n6. Ability to communicate pros and cons of solutions and garner buy-in for leaders\n\n**Customer Focused**\n\n1. Strong customer focus\n2. Experience in scaling document generation processes to handle increased demands efficiently\n3. Ability to prioritize accuracy and precision in document generation\n\n**Problem-solving and Leadership**\n\n1. Strong problem-solving skills\n2. Leadership capabilities to inspire and mentor team members\n3. Fostering a culture of continuous improvement and excellence', pdf_path='', recruiter_link=''), error: Traceback (most recent call last):
  File "E:\Test\Auto_Jobs_Applier_AIHawk\src\aihawk_easy_applier.py", line 137, in job_apply
    self._fill_application_form(job)
  File "E:\Test\Auto_Jobs_Applier_AIHawk\src\aihawk_easy_applier.py", line 279, in _fill_application_form
    if self._next_or_submit():
       ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Test\Auto_Jobs_Applier_AIHawk\src\aihawk_easy_applier.py", line 297, in _next_or_submit
    self._check_for_errors()
  File "E:\Test\Auto_Jobs_Applier_AIHawk\src\aihawk_easy_applier.py", line 313, in _check_for_errors
    raise Exception(f"Failed answering or file upload. {str([e.text for e in error_elements])}")
Exception: Failed answering or file upload. ['Please enter a valid answer']

### Branch

main

### Python version

3.11.9

### LLM Used

Ollama

### Model used

llama3.2:latest

**Comment by TheLocalLab** [comment]
Yeah this is happening with me as well. I tried three different local models running with ollama(llama3.2, llama3.1 and gemma2) and the same things keep on happening. When on the easy apply page, the model clears the email field, even though it seems that its suppose to select one from the dropdown because I currently have two different emails on my account. Also it changes the phone country code to Saint Vincent from the US and uses a preexisting answer for the mobile phone number field that it finds, "Found existing answer" as written in the terminal, instead of using the number in the plain text resume yaml file. The "Found existing answer" feature appears to be using old inputs with complete disregard of changes that could of been made in the yaml file.

**Comment by queukat** [comment]
Found existing answer for question 'phone country code
phone country code': Democratic Republic of the Congo (+243)

just fix or delete this answer in answers.json (it's your local file which keep answers)
