### ISSUE TITLE
[HELP WANTED]: <Provide a descriptive title>

### ISSUE THREAD

**Issue by ozkolok12** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#514]
### Issue description

Hi everybody! I'm trying to launch the script, but all the time is getting this:
`= RESTART: C:\Users\Hoz\Auto_Jobs_Applier_AIHawk\main.py
Traceback (most recent call last):
  File "C:\Users\Hoz\Auto_Jobs_Applier_AIHawk\main.py", line 11, in <module>
    from lib_resume_builder_AIHawk import Resume,StyleManager,FacadeManager,ResumeGenerator
  File "C:\Users\Hoz\AppData\Local\Programs\Python\Python312\Lib\site-packages\lib_resume_builder_AIHawk\__init__.py", line 5, in <module>
    from .manager_facade import FacadeManager
  File "C:\Users\Hoz\AppData\Local\Programs\Python\Python312\Lib\site-packages\lib_resume_builder_AIHawk\manager_facade.py", line 5, in <module>
    import inquirer
  File "C:\Users\Hoz\AppData\Local\Programs\Python\Python312\Lib\site-packages\inquirer\__init__.py", line 1, in <module>
    from inquirer.prompt import prompt
  File "C:\Users\Hoz\AppData\Local\Programs\Python\Python312\Lib\site-packages\inquirer\prompt.py", line 1, in <module>
    import inquirer.themes as themes
  File "C:\Users\Hoz\AppData\Local\Programs\Python\Python312\Lib\site-packages\inquirer\themes.py", line 9, in <module>
    term = Terminal()
  File "C:\Users\Hoz\AppData\Local\Programs\Python\Python312\Lib\site-packages\blessed\terminal.py", line 164, in __init__
    self.__init__streams()
  File "C:\Users\Hoz\AppData\Local\Programs\Python\Python312\Lib\site-packages\blessed\terminal.py", line 253, in __init__streams
    self._init_descriptor = sys.__stdout__.fileno()
AttributeError: 'NoneType' object has no attribute 'fileno'`

Who knows, what the error is it? And what should I do to solve it. 
I did everything according to instruction
![Clipboard-1](https://github.com/user-attachments/assets/085beec7-62c7-4e3b-85fa-71be62383e7f)

**Comment by queukat** [comment]
try PowerShell or CMD shell

**Comment by ozkolok12** [comment]
> try PowerShell or CMD shell

I did, and get a word "Python". Is it as it should be?
![image](https://github.com/user-attachments/assets/54557d06-fc23-447c-85e1-c740656051a7)

**Comment by mohammadi-com** [comment]
Have created and used virtual environments?
I see from shell that you've not activated the virtual environment.
Follow instructions from here, hope it helps: https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk#:~:text=Activate%20virtual%20environment%3A

**Comment by ozkolok12** [comment]
> Have created and used virtual environment? I see from shell that you've not activated the virtual environment. Follow instructions from here, hope it helps: https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk#:~:text=Activate%20virtual%20environment%3A

Thanks for reply! Yeah, it seems there is persistent error with virtual environment creation. After I pasted all necessary commands, I got a reply, that system couldn't find a folder "virtual". Stuck on that(
