### ISSUE TITLE
[BUG]:  xpath issue again after hotfix

### ISSUE THREAD

**Issue by krzemienski** [AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent#959]
### Describe the bug

2024-11-26 21:04:00.805 | WARNING  | ai_hawk.job_manager:get_jobs_from_page:276 - No job results found on the page.  expection: Traceback (most recent call last):   File "/Users/nick/Desktop/Auto_Jobs_Applier_AIHawk/src/ai_hawk/job_manager.py", line 258, in get_jobs_from_page     jobs_container = self.driver.find_element(By.XPATH, jobs_xpath_query)                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/Users/nick/Library/Python/3.12/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 831, in find_element     return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/Users/nick/Library/Python/3.12/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute     self.error_handler.check_response(response)   File "/Users/nick/Library/Python/3.12/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response     raise exception_class(message, screen, stacktrace) selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//ul[contains(@class, 'scaffold-layout__list-container')]"}   (Session info: chrome=131.0.6778.86) Stacktrace: 0   chromedriver                        0x0000000102fbbac4 cxxbridge1$str$ptr + 3651580 1   chromedriver                        0x0000000102fb4314 cxxbridge1$str$ptr + 3620940 2   chromedriver                        0x0000000102a1c4b4 cxxbridge1$string$len + 89224 3   chromedriver                        0x0000000102a60898 cxxbridge1$string$len + 368748 4   chromedriver                        0x0000000102a9a0fc cxxbridge1$string$len + 604368 5   chromedriver                        0x0000000102a550b0 cxxbridge1$string$len + 321668 6   chromedriver                        0x0000000102a55d00 cxxbridge1$string$len + 324820 7   chromedriver                        0x0000000102f86e08 cxxbridge1$str$ptr + 3435328 8   chromedriver                        0x0000000102f8a120 cxxbridge1$str$ptr + 3448408 9   chromedriver                        0x0000000102f6e17c cxxbridge1$str$ptr + 3333812 10  chromedriver                        0x0000000102f8a9e0 cxxbridge1$str$ptr + 3450648 11  chromedriver                        0x0000000102f5f988 cxxbridge1$str$ptr + 3274432 12  chromedriver                        0x0000000102fa50f4 cxxbridge1$str$ptr + 3558956 13  chromedriver                        0x0000000102fa5270 cxxbridge1$str$ptr + 3559336 14  chromedriver                        0x0000000102fb3f88 cxxbridge1$str$ptr + 3620032 15  libsystem_pthread.dylib             0x00000001866682e4 _pthread_start + 136 16  libsystem_pthread.dylib             0x00000001866630fc thread_start + 8

### Steps to reproduce

I am using the main branch and was following the thread and pull request issues for the hotfix #924 and have ensured that my code locally is that with the hotfix changes in job manager.

So this code was ran on main and ensured that the job manager does have the pathfixing for that were made in the last two days. I then went ahead and went to try to run it again about 10 minutes ago and now it seems to be finding another XPath issue related to the same list. I just figured I would post this up quickly so that everyone is aware again. I was going to go ahead and try to figure out the changes needed over the evening into tomorrow. 

Regardless, Happy Thanksgiving to everybody in the United States and thank you for this project. 

```
2024-11-26 21:04:00.805 | WARNING  | ai_hawk.job_manager:get_jobs_from_page:276 - No job results found on the page.  expection: Traceback (most recent call last):   File "/Users/nick/Desktop/Auto_Jobs_Applier_AIHawk/src/ai_hawk/job_manager.py", line 258, in get_jobs_from_page     jobs_container = self.driver.find_element(By.XPATH, jobs_xpath_query)                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/Users/nick/Library/Python/3.12/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 831, in find_element     return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/Users/nick/Library/Python/3.12/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute     self.error_handler.check_response(response)   File "/Users/nick/Library/Python/3.12/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response     raise exception_class(message, screen, stacktrace) selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//ul[contains(@class, 'scaffold-layout__list-container')]"}   (Session info: chrome=131.0.6778.86) Stacktrace: 0   chromedriver                        0x0000000102fbbac4 cxxbridge1$str$ptr + 3651580 1   chromedriver                        0x0000000102fb4314 cxxbridge1$str$ptr + 3620940 2   chromedriver                        0x0000000102a1c4b4 cxxbridge1$string$len + 89224 3   chromedriver                        0x0000000102a60898 cxxbridge1$string$len + 368748 4   chromedriver                        0x0000000102a9a0fc cxxbridge1$string$len + 604368 5   chromedriver                        0x0000000102a550b0 cxxbridge1$string$len + 321668 6   chromedriver                        0x0000000102a55d00 cxxbridge1$string$len + 324820 7   chromedriver                        0x0000000102f86e08 cxxbridge1$str$ptr + 3435328 8   chromedriver                        0x0000000102f8a120 cxxbridge1$str$ptr + 3448408 9   chromedriver                        0x0000000102f6e17c cxxbridge1$str$ptr + 3333812 10  chromedriver                        0x0000000102f8a9e0 cxxbridge1$str$ptr + 3450648 11  chromedriver                        0x0000000102f5f988 cxxbridge1$str$ptr + 3274432 12  chromedriver                        0x0000000102fa50f4 cxxbridge1$str$ptr + 3558956 13  chromedriver                        0x0000000102fa5270 cxxbridge1$str$ptr + 3559336 14  chromedriver                        0x0000000102fb3f88 cxxbridge1$str$ptr + 3620032 15  libsystem_pthread.dylib             0x00000001866682e4 _pthread_start + 136 16  libsystem_pthread.dylib             0x00000001866630fc thread_start + 8
```

### Branch

main

**Comment by sladinji** [comment]
Hi,

I have the same issue with Python 3.12 on MacOS. 

Regards,

Julien

**Comment by ilushka999** [comment]
confirm. same issue

**Comment by brcnwankwo** [comment]
same issue

**Comment by craschnet** [comment]
Same Issue

**Comment by kayo12** [comment]
Same issue

**Comment by max870701** [comment]
Same issue.
